/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entites.Chambre;
import entites.Client;
import javax.swing.table.DefaultTableModel;
import service.ReservationService;
import entites.Reservation;
import java.util.Date;

import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import service.ChamberService;
import service.ClientService;

/**
 *
 * @author pc
 */
public class ReservationFrom extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservationFrom
     */
    private ReservationService Rs;
    private ClientService Cs;
    private ChamberService Chs;
    private DefaultTableModel Tmodel;
    private DefaultTableModel Tmodel2;
    private static int id;

    public ReservationFrom() {
        initComponents();
        Rs = new ReservationService();
        Cs = new ClientService();
        Chs = new ChamberService();

        Tmodel = (DefaultTableModel) listeReservation.getModel();
        this.setTitle("Gestion des Reservations");
        Tmodel2= (DefaultTableModel) listeChmbre.getModel();
        LoadCleint();
        LoadChambre();
        load();
    }

    private void LoadCleint() {
        for (Client C : Cs.findAll()) {
            Filed_client.addItem(C);
            Filed_clientBTD.addItem(C);
        }
    }

    private void LoadChambre() {
        for (Chambre ch : Chs.findAll()) {
            Filed_chmbre.addItem(ch);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooserBeanInfo1 = new com.toedter.calendar.JMonthChooserBeanInfo();
        jDayChooserBeanInfo1 = new com.toedter.calendar.JDayChooserBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton1Ajouter = new javax.swing.JButton();
        jButton2Modifier = new javax.swing.JButton();
        jButton3Supprimer = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Filed_client = new javax.swing.JComboBox();
        Filed_chmbre = new javax.swing.JComboBox();
        Filed_DateDeb = new com.toedter.calendar.JDateChooser();
        Filed_DateFin = new com.toedter.calendar.JDateChooser();
        Clear1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listeReservation = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Filed_DateDebBTD = new com.toedter.calendar.JDateChooser();
        Filed_DateFinBTD = new com.toedter.calendar.JDateChooser();
        Filed_clientBTD = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        print1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listeChmbre = new javax.swing.JTable();
        print2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouveau Reservation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setAutoscrolls(true);

        jLabel1.setText("Id");

        jLabel2.setText("Date debut");

        jLabel3.setText("Chambre");

        jLabel4.setText("Client");

        jTextField1_id.setEnabled(false);

        jButton1Ajouter.setText("Ajouter");
        jButton1Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AjouterActionPerformed(evt);
            }
        });

        jButton2Modifier.setText("Modifier");
        jButton2Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ModifierActionPerformed(evt);
            }
        });

        jButton3Supprimer.setText("Supprimer");
        jButton3Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SupprimerActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel5.setText("Date Fin");

        Filed_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filed_clientActionPerformed(evt);
            }
        });

        Clear1.setText("report");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });

        listeReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date debut", "Date Fin", "Chambre", "Client"
            }
        ));
        listeReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeReservationMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listeReservation);
        if (listeReservation.getColumnModel().getColumnCount() > 0) {
            listeReservation.getColumnModel().getColumn(3).setHeaderValue("Chambre");
            listeReservation.getColumnModel().getColumn(4).setHeaderValue("Client");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filed_client, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filed_DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filed_DateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1_id, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(Filed_chmbre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1Ajouter)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Filed_DateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton2Modifier))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Filed_DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear1))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Filed_chmbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton3Supprimer))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Filed_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cherecher les chambres réservé entre deux dates"));

        Filed_clientBTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Filed_clientBTDMouseClicked(evt);
            }
        });

        jLabel6.setText("Date debut");

        jLabel7.setText("Date Fin");

        jLabel8.setText("Client");

        print1.setText("Chercher");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });

        listeChmbre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Telephone", "Categorie"
            }
        ));
        listeChmbre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeChmbreMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listeChmbre);

        print2.setText("Statistique");
        print2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Filed_DateDebBTD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Filed_DateFinBTD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Filed_clientBTD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(173, 173, 173)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(print1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(print2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Filed_DateFinBTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Filed_clientBTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(print1)
                            .addComponent(print2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filed_DateDebBTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeReservationMouseClicked
        id = Integer.parseInt(Tmodel.getValueAt(listeReservation.getSelectedRow(), 0).toString());
        jTextField1_id.setText(Tmodel.getValueAt(listeReservation.getSelectedRow(),0).toString());
        Filed_DateDeb.setDate((Date) Tmodel.getValueAt(listeReservation.getSelectedRow(), 1));
        // System.out.println();Filed_DateDeb.setDate((Date) Tmodel.getValueAt(listeReservation.getSelectedRow(),1));
        Filed_DateFin.setDate((Date) Tmodel.getValueAt(listeReservation.getSelectedRow(), 2));
        Filed_chmbre.getModel().setSelectedItem(Tmodel.getValueAt(listeReservation.getSelectedRow(), 3));
        Filed_client.getModel().setSelectedItem(Tmodel.getValueAt(listeReservation.getSelectedRow(), 4));
    }//GEN-LAST:event_listeReservationMouseClicked

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

    }//GEN-LAST:event_ClearActionPerformed

    private void jButton3SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SupprimerActionPerformed

            int response = JOptionPane.showConfirmDialog(this, "voulez-vous supprimer cette reservation");
            if(response == 0){
                
                
                Rs.delete(Rs.findById(id));
                JOptionPane.showMessageDialog(this, "votre ligne a ete supprimée");
                load();
            }
            
        
        
        
    }//GEN-LAST:event_jButton3SupprimerActionPerformed

    private void jButton2ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ModifierActionPerformed

        Date DateDeb = Filed_DateDeb.getDate();
        Date DateFin = Filed_DateFin.getDate();
        Chambre ch = (Chambre) Filed_chmbre.getSelectedItem();
        Client cl = (Client) Filed_client.getSelectedItem();

        // Reservation r = Rs.findById(id);
        Reservation r = new Reservation(id, DateDeb, DateFin, ch, cl);
        // r.setDateDebut(DateDeb);r.setDateFin(DateFin);
        // r.setChambre(ch);r.setClient(cl);

        if (Rs.update(r)) {
            JOptionPane.showMessageDialog(this, "reservation modi");
        }
        System.out.println("date F : " + DateFin + "date d : " + DateDeb + " id " + id + " cl " + cl + " chmb " + ch);
        load();


    }//GEN-LAST:event_jButton2ModifierActionPerformed

    private void jButton1AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AjouterActionPerformed
        Date DateDeb = Filed_DateDeb.getDate();
        Date DateFin = Filed_DateFin.getDate();
        Chambre ch = (Chambre) Filed_chmbre.getSelectedItem();
        Client cl = (Client) Filed_client.getSelectedItem();
        if(Rs.verifierRes(ch, DateDeb, DateFin)){
            if (Rs.create(new Reservation(DateDeb, DateFin, ch, cl))) {
            JOptionPane.showMessageDialog(this, "cree");
        } else {
            JOptionPane.showMessageDialog(this, "ereur");
        }            
        }else {
             JOptionPane.showMessageDialog(this, "Chambre deja reservé");
        }
        
        load();
        

    }//GEN-LAST:event_jButton1AjouterActionPerformed

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed

        // String value1 = jTextField1_id.getText();
        //Date Value2 = Filed_DateDeb.getDate();
        //Date Value3 = Filed_DateFin.getDate();
       /* String value2 = Filed_DateDeb.getDate().toString();
         String value3 = Filed_DateFin.getDate().toString();
         String ch =  Filed_chmbre.getSelectedItem().toString();
         String cl =  Filed_client.getSelectedItem().toString();*/
        try {
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream("Report.pdf"));
            doc.open();

            PdfPTable table = new PdfPTable(4);
            table.addCell("Date debut");
            table.addCell("Date Fin");
            table.addCell("Chambre");
            table.addCell("Client");
            for (Reservation cl : Rs.findAll()) {

                table.addCell(cl.getDateDebut().toString());
                table.addCell(cl.getDateFin().toString());
                table.addCell(cl.getChambre().toString());
                table.addCell(cl.getClient().toString());

            }
            doc.add(table);

            doc.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_Clear1ActionPerformed

    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        Date d1 = Filed_DateDebBTD.getDate();
        Date d2 = Filed_DateFinBTD.getDate();
        Client cl = (Client) Filed_clientBTD.getSelectedItem();

        Tmodel2.setRowCount(0);
        for (Chambre ch : Rs.findChambreBetweenDates(cl, d1, d2)) {

            Tmodel2.addRow(new Object[]{
                ch.getId(),
                ch.getTelephone(),
                ch.getCategorie(),});
            System.out.println(ch.getId()+" "+ch.getTelephone()+" "+ch.getCategorie().getId());
           // JOptionPane.showMessageDialog(this,  ch.getId());
        }
        


    }//GEN-LAST:event_print1ActionPerformed

    private void listeChmbreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeChmbreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listeChmbreMouseClicked

    private void Filed_clientBTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Filed_clientBTDMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Filed_clientBTDMouseClicked

    private void print2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print2ActionPerformed
        // TODO add your handling code here:
        Client cl = (Client) Filed_clientBTD.getSelectedItem();
        
          
        
        String query ="select YEAR(`dateDebut`) as Annee ,count(YEAR(`dateDebut`)) as NB_Res  from reservation where id_client = "+cl.getId()+" GROUP by year(`dateDebut`);  ";
   
        try {
            
            JDBCCategoryDataset dataser= new JDBCCategoryDataset(connection.Connexion.getCon(),query);
            JFreeChart chart = ChartFactory.createBarChart("Nombre de reservation chaque annee", "Annee", "Nb Reservation de "+cl.getNom(), dataser);
            BarRenderer rend = null;
            CategoryPlot plot = null; 
            rend= new BarRenderer();
            ChartFrame frame= new ChartFrame("Statistique",chart);
            frame.setVisible(true);
            frame.setSize(400,600);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(chart1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_print2ActionPerformed

    private void Filed_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filed_clientActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Filed_clientActionPerformed
 /**/
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Clear1;
    private com.toedter.calendar.JDateChooser Filed_DateDeb;
    private com.toedter.calendar.JDateChooser Filed_DateDebBTD;
    private com.toedter.calendar.JDateChooser Filed_DateFin;
    private com.toedter.calendar.JDateChooser Filed_DateFinBTD;
    private javax.swing.JComboBox Filed_chmbre;
    private javax.swing.JComboBox Filed_client;
    private javax.swing.JComboBox Filed_clientBTD;
    private javax.swing.JButton jButton1Ajouter;
    private javax.swing.JButton jButton2Modifier;
    private javax.swing.JButton jButton3Supprimer;
    private com.toedter.calendar.JDayChooserBeanInfo jDayChooserBeanInfo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JMonthChooserBeanInfo jMonthChooserBeanInfo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    javax.swing.JTextField jTextField1_id;
    private javax.swing.JTable listeChmbre;
    private javax.swing.JTable listeReservation;
    private javax.swing.JButton print1;
    private javax.swing.JButton print2;
    // End of variables declaration//GEN-END:variables

    public void load() {
        Tmodel.setRowCount(0);
        for (Reservation cl : Rs.findAll()) {
            Tmodel.addRow(new Object[]{
                cl.getId(),
                cl.getDateDebut(),
                cl.getDateFin(),
                cl.getChambre(),
                cl.getClient()});

        }
    }
}
